OBJS	= serial.o
HEADER	= types.h utils.h activations/leakyrelu.h activations/relu.h layers/conv.h layers/net.h layers/linear.h layers/layer.h
OUT		= runserial
CC	 	= g++
FLAGS	= -g -c -Wall -I/usr/include/eigen3/ -O3
LFLAGS	= -lm

all: clean $(OBJS)
	$(CC) -g $(OBJS) -o $(OUT) $(LFLAGS)

serial.o: ./exps/serial.cpp
	$(CC) $(FLAGS) ./exps/serial.cpp -std=c++17

test.o: clean ./exps/test.cpp
	$(CC) $(FLAGS) ./exps/test.cpp -std=c++17

.PHONY: clean
clean:
	rm -f $(OBJS) $(OUT)
